If you have not used sqlite3 previously:
	sqlite3: sqlite3.c 
	$gcc sqlite3.c -c 

client: client.cpp
	$(CC) client.cpp -o client 
	./client localhost

server: server.cpp
	$(CC) server.cpp -std=c++11 -ldl -pthread sqlite3.o -o server 
	./server
